services:

  app:
    build: .
    container_name: my-app1
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/nest-essentials-typeorm

  db:
    image: mysql:8.0.37-debian
    container_name: my-db1
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nest
    ports:
      - 3306:3306
    volumes:
    - ./.docker/mysql:/docker-entrypoint-initdb.d
      # - ./docker/dbdata:/var/lib/mysql